### ISSUE TITLE
我找到了睡眠失败的原因

### ISSUE THREAD

**Issue by haoyaxuan** [Heporis/Hackintosh-OptiPlex-3050MT#3]
原因是因为音频的IRQ补丁。去掉补丁睡眠正常，但是没有音频。打上补丁睡眠无法唤醒，只能重启。

**Comment by Heporis** [comment]
还有这种bug？有解决方法吗？

**Comment by haoyaxuan** [comment]
> 还有这种bug？有解决方法吗？

我还未研究出来，估计需要自己写ssdt补丁，也可以用万能声卡驱动，但是会爆音。

**Comment by haoyaxuan** [comment]
我已经解决了睡眠问题，是采用万能声卡驱动，最新版的万能声卡驱动，测试未出现爆音。你可以看下我的仓库：Dell-OptiPlex-5050。
